/**
 * GENERATED by scripts/subset-seal-font.mjs (Task G2a). Do not edit by hand.
 *
 * public/fonts/seal-glyphs.woff2 is Noto Serif TC Regular (SIL Open Font
 * License 1.1) subset to exactly these characters. The @font-face is in
 * app/globals.css ("Oh Seal Glyphs"). Re-run the script after adding a glyph
 * to seals.ts; seal.test.tsx fails until you do.
 */
export const SEAL_FONT_FAMILY = "Oh Seal Glyphs";
export const SEAL_FONT_GLYPHS = "初麵迷百友星尊連週傳全辣探宴晨元牛先午夜豪善遊回贈印";
