// GENERATED by scripts/site-images.mjs. Do not edit by hand.
// Re-run `node scripts/site-images.mjs` after changing the mapping in that
// file (it also regenerates apps/web/public/site/*.{avif,webp}).

export type ImageKey =
  | "storefront-dusk"
  | "storefront-queue"
  | "hall-rows"
  | "hall-rows-alt"
  | "pod-hatch-a"
  | "pod-hatch-b"
  | "pod-hatch-c"
  | "bowl-slices-top"
  | "bowl-slices-side"
  | "beef-macro"
  | "bowl-chunks-top"
  | "bowl-chunks-side"
  | "store-interior"
  | "bowl-empty"
  | "bowl-flatlay"
  | "chopsticks"
  | "sign-pool";

// Dotted next-intl message key, e.g. "siteImages.storefrontDusk".
export type MessageKey = `siteImages.${string}`;

export interface SiteImage {
  src: { avif: string; webp: string };
  w: number;
  h: number;
  alt: MessageKey;
}

export const SITE_IMAGES: Record<ImageKey, SiteImage> = {
  "storefront-dusk": {
    src: { avif: "/site/storefront-dusk-1200.avif", webp: "/site/storefront-dusk-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.storefrontDusk",
  },
  "storefront-queue": {
    src: { avif: "/site/storefront-queue-1200.avif", webp: "/site/storefront-queue-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.storefrontQueue",
  },
  "hall-rows": {
    src: { avif: "/site/hall-rows-1200.avif", webp: "/site/hall-rows-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.hallRows",
  },
  "hall-rows-alt": {
    src: { avif: "/site/hall-rows-alt-1200.avif", webp: "/site/hall-rows-alt-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.hallRowsAlt",
  },
  "pod-hatch-a": {
    src: { avif: "/site/pod-hatch-a-1200.avif", webp: "/site/pod-hatch-a-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.podHatchA",
  },
  "pod-hatch-b": {
    src: { avif: "/site/pod-hatch-b-1200.avif", webp: "/site/pod-hatch-b-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.podHatchB",
  },
  "pod-hatch-c": {
    src: { avif: "/site/pod-hatch-c-1200.avif", webp: "/site/pod-hatch-c-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.podHatchC",
  },
  "bowl-slices-top": {
    src: { avif: "/site/bowl-slices-top-1200.avif", webp: "/site/bowl-slices-top-1200.webp" },
    w: 1200,
    h: 1200,
    alt: "siteImages.bowlSlicesTop",
  },
  "bowl-slices-side": {
    src: { avif: "/site/bowl-slices-side-1200.avif", webp: "/site/bowl-slices-side-1200.webp" },
    w: 1024,
    h: 1024,
    alt: "siteImages.bowlSlicesSide",
  },
  "beef-macro": {
    src: { avif: "/site/beef-macro-1200.avif", webp: "/site/beef-macro-1200.webp" },
    w: 1024,
    h: 1024,
    alt: "siteImages.beefMacro",
  },
  "bowl-chunks-top": {
    src: { avif: "/site/bowl-chunks-top-1200.avif", webp: "/site/bowl-chunks-top-1200.webp" },
    w: 1200,
    h: 1200,
    alt: "siteImages.bowlChunksTop",
  },
  "bowl-chunks-side": {
    src: { avif: "/site/bowl-chunks-side-1200.avif", webp: "/site/bowl-chunks-side-1200.webp" },
    w: 1024,
    h: 1024,
    alt: "siteImages.bowlChunksSide",
  },
  "store-interior": {
    src: { avif: "/site/store-interior-1200.avif", webp: "/site/store-interior-1200.webp" },
    w: 1024,
    h: 1024,
    alt: "siteImages.storeInterior",
  },
  "bowl-empty": {
    src: { avif: "/site/bowl-empty-1200.avif", webp: "/site/bowl-empty-1200.webp" },
    w: 1024,
    h: 1024,
    alt: "siteImages.bowlEmpty",
  },
  "bowl-flatlay": {
    src: { avif: "/site/bowl-flatlay-1200.avif", webp: "/site/bowl-flatlay-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.bowlFlatlay",
  },
  "chopsticks": {
    src: { avif: "/site/chopsticks-1200.avif", webp: "/site/chopsticks-1200.webp" },
    w: 1024,
    h: 1024,
    alt: "siteImages.chopsticks",
  },
  "sign-pool": {
    src: { avif: "/site/sign-pool-1200.avif", webp: "/site/sign-pool-1200.webp" },
    w: 1200,
    h: 900,
    alt: "siteImages.signPool",
  },
};
