// GENERATED by scripts/site-images.mjs. Do not edit by hand.
// Re-run `node scripts/site-images.mjs` after changing the mapping in that
// file (it also regenerates apps/web/public/site/*.{avif,webp}).

export type ImageKey =
  | "storefront-dusk"
  | "storefront-queue"
  | "hall-rows"
  | "hall-rows-alt"
  | "pod-hatch-a"
  | "pod-hatch-b"
  | "pod-hatch-c"
  | "bowl-slices-top"
  | "bowl-slices-side"
  | "beef-macro"
  | "bowl-chunks-top"
  | "bowl-chunks-side"
  | "store-interior"
  | "bowl-empty"
  | "bowl-flatlay"
  | "chopsticks"
  | "sign-pool";

// Dotted next-intl message key, e.g. "siteImages.storefrontDusk".
export type MessageKey = `siteImages.${string}`;

export interface SiteImage {
  // The largest (1200w) file in each format. Used as the <img> fallback's
  // base and as a plain single-image src for callers that don't need a
  // <picture>.
  src: { avif: string; webp: string };
  // A full `srcset` attribute string ("/site/key-390.avif 390w, ...") built
  // from every generated width (390/780/1200), for responsive <source> tags.
  srcSet: { avif: string; webp: string };
  w: number;
  h: number;
  alt: MessageKey;
}

export const SITE_IMAGES: Record<ImageKey, SiteImage> = {
  "storefront-dusk": {
    src: { avif: "/site/storefront-dusk-1200.avif", webp: "/site/storefront-dusk-1200.webp" },
    srcSet: { avif: "/site/storefront-dusk-390.avif 390w, /site/storefront-dusk-780.avif 780w, /site/storefront-dusk-1200.avif 1200w", webp: "/site/storefront-dusk-390.webp 390w, /site/storefront-dusk-780.webp 780w, /site/storefront-dusk-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.storefrontDusk",
  },
  "storefront-queue": {
    src: { avif: "/site/storefront-queue-1200.avif", webp: "/site/storefront-queue-1200.webp" },
    srcSet: { avif: "/site/storefront-queue-390.avif 390w, /site/storefront-queue-780.avif 780w, /site/storefront-queue-1200.avif 1200w", webp: "/site/storefront-queue-390.webp 390w, /site/storefront-queue-780.webp 780w, /site/storefront-queue-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.storefrontQueue",
  },
  "hall-rows": {
    src: { avif: "/site/hall-rows-1200.avif", webp: "/site/hall-rows-1200.webp" },
    srcSet: { avif: "/site/hall-rows-390.avif 390w, /site/hall-rows-780.avif 780w, /site/hall-rows-1200.avif 1200w", webp: "/site/hall-rows-390.webp 390w, /site/hall-rows-780.webp 780w, /site/hall-rows-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.hallRows",
  },
  "hall-rows-alt": {
    src: { avif: "/site/hall-rows-alt-1200.avif", webp: "/site/hall-rows-alt-1200.webp" },
    srcSet: { avif: "/site/hall-rows-alt-390.avif 390w, /site/hall-rows-alt-780.avif 780w, /site/hall-rows-alt-1200.avif 1200w", webp: "/site/hall-rows-alt-390.webp 390w, /site/hall-rows-alt-780.webp 780w, /site/hall-rows-alt-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.hallRowsAlt",
  },
  "pod-hatch-a": {
    src: { avif: "/site/pod-hatch-a-1200.avif", webp: "/site/pod-hatch-a-1200.webp" },
    srcSet: { avif: "/site/pod-hatch-a-390.avif 390w, /site/pod-hatch-a-780.avif 780w, /site/pod-hatch-a-1200.avif 1200w", webp: "/site/pod-hatch-a-390.webp 390w, /site/pod-hatch-a-780.webp 780w, /site/pod-hatch-a-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.podHatchA",
  },
  "pod-hatch-b": {
    src: { avif: "/site/pod-hatch-b-1200.avif", webp: "/site/pod-hatch-b-1200.webp" },
    srcSet: { avif: "/site/pod-hatch-b-390.avif 390w, /site/pod-hatch-b-780.avif 780w, /site/pod-hatch-b-1200.avif 1200w", webp: "/site/pod-hatch-b-390.webp 390w, /site/pod-hatch-b-780.webp 780w, /site/pod-hatch-b-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.podHatchB",
  },
  "pod-hatch-c": {
    src: { avif: "/site/pod-hatch-c-1200.avif", webp: "/site/pod-hatch-c-1200.webp" },
    srcSet: { avif: "/site/pod-hatch-c-390.avif 390w, /site/pod-hatch-c-780.avif 780w, /site/pod-hatch-c-1200.avif 1200w", webp: "/site/pod-hatch-c-390.webp 390w, /site/pod-hatch-c-780.webp 780w, /site/pod-hatch-c-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.podHatchC",
  },
  "bowl-slices-top": {
    src: { avif: "/site/bowl-slices-top-1200.avif", webp: "/site/bowl-slices-top-1200.webp" },
    srcSet: { avif: "/site/bowl-slices-top-390.avif 390w, /site/bowl-slices-top-780.avif 780w, /site/bowl-slices-top-1200.avif 1200w", webp: "/site/bowl-slices-top-390.webp 390w, /site/bowl-slices-top-780.webp 780w, /site/bowl-slices-top-1200.webp 1200w" },
    w: 1200,
    h: 1200,
    alt: "siteImages.bowlSlicesTop",
  },
  "bowl-slices-side": {
    src: { avif: "/site/bowl-slices-side-1200.avif", webp: "/site/bowl-slices-side-1200.webp" },
    srcSet: { avif: "/site/bowl-slices-side-390.avif 390w, /site/bowl-slices-side-780.avif 780w, /site/bowl-slices-side-1200.avif 1200w", webp: "/site/bowl-slices-side-390.webp 390w, /site/bowl-slices-side-780.webp 780w, /site/bowl-slices-side-1200.webp 1200w" },
    w: 1024,
    h: 1024,
    alt: "siteImages.bowlSlicesSide",
  },
  "beef-macro": {
    src: { avif: "/site/beef-macro-1200.avif", webp: "/site/beef-macro-1200.webp" },
    srcSet: { avif: "/site/beef-macro-390.avif 390w, /site/beef-macro-780.avif 780w, /site/beef-macro-1200.avif 1200w", webp: "/site/beef-macro-390.webp 390w, /site/beef-macro-780.webp 780w, /site/beef-macro-1200.webp 1200w" },
    w: 1024,
    h: 1024,
    alt: "siteImages.beefMacro",
  },
  "bowl-chunks-top": {
    src: { avif: "/site/bowl-chunks-top-1200.avif", webp: "/site/bowl-chunks-top-1200.webp" },
    srcSet: { avif: "/site/bowl-chunks-top-390.avif 390w, /site/bowl-chunks-top-780.avif 780w, /site/bowl-chunks-top-1200.avif 1200w", webp: "/site/bowl-chunks-top-390.webp 390w, /site/bowl-chunks-top-780.webp 780w, /site/bowl-chunks-top-1200.webp 1200w" },
    w: 1200,
    h: 1200,
    alt: "siteImages.bowlChunksTop",
  },
  "bowl-chunks-side": {
    src: { avif: "/site/bowl-chunks-side-1200.avif", webp: "/site/bowl-chunks-side-1200.webp" },
    srcSet: { avif: "/site/bowl-chunks-side-390.avif 390w, /site/bowl-chunks-side-780.avif 780w, /site/bowl-chunks-side-1200.avif 1200w", webp: "/site/bowl-chunks-side-390.webp 390w, /site/bowl-chunks-side-780.webp 780w, /site/bowl-chunks-side-1200.webp 1200w" },
    w: 1024,
    h: 1024,
    alt: "siteImages.bowlChunksSide",
  },
  "store-interior": {
    src: { avif: "/site/store-interior-1200.avif", webp: "/site/store-interior-1200.webp" },
    srcSet: { avif: "/site/store-interior-390.avif 390w, /site/store-interior-780.avif 780w, /site/store-interior-1200.avif 1200w", webp: "/site/store-interior-390.webp 390w, /site/store-interior-780.webp 780w, /site/store-interior-1200.webp 1200w" },
    w: 1024,
    h: 1024,
    alt: "siteImages.storeInterior",
  },
  "bowl-empty": {
    src: { avif: "/site/bowl-empty-1200.avif", webp: "/site/bowl-empty-1200.webp" },
    srcSet: { avif: "/site/bowl-empty-390.avif 390w, /site/bowl-empty-780.avif 780w, /site/bowl-empty-1200.avif 1200w", webp: "/site/bowl-empty-390.webp 390w, /site/bowl-empty-780.webp 780w, /site/bowl-empty-1200.webp 1200w" },
    w: 1024,
    h: 1024,
    alt: "siteImages.bowlEmpty",
  },
  "bowl-flatlay": {
    src: { avif: "/site/bowl-flatlay-1200.avif", webp: "/site/bowl-flatlay-1200.webp" },
    srcSet: { avif: "/site/bowl-flatlay-390.avif 390w, /site/bowl-flatlay-780.avif 780w, /site/bowl-flatlay-1200.avif 1200w", webp: "/site/bowl-flatlay-390.webp 390w, /site/bowl-flatlay-780.webp 780w, /site/bowl-flatlay-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.bowlFlatlay",
  },
  "chopsticks": {
    src: { avif: "/site/chopsticks-1200.avif", webp: "/site/chopsticks-1200.webp" },
    srcSet: { avif: "/site/chopsticks-390.avif 390w, /site/chopsticks-780.avif 780w, /site/chopsticks-1200.avif 1200w", webp: "/site/chopsticks-390.webp 390w, /site/chopsticks-780.webp 780w, /site/chopsticks-1200.webp 1200w" },
    w: 1024,
    h: 1024,
    alt: "siteImages.chopsticks",
  },
  "sign-pool": {
    src: { avif: "/site/sign-pool-1200.avif", webp: "/site/sign-pool-1200.webp" },
    srcSet: { avif: "/site/sign-pool-390.avif 390w, /site/sign-pool-780.avif 780w, /site/sign-pool-1200.avif 1200w", webp: "/site/sign-pool-390.webp 390w, /site/sign-pool-780.webp 780w, /site/sign-pool-1200.webp 1200w" },
    w: 1200,
    h: 900,
    alt: "siteImages.signPool",
  },
};
