"use client";

import { useEffect, useState } from "react";

const BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";

/**
 * Chappy Chopstix pops in at the top of the order page with a short, fun,
 * personalized line based on the attendee's name and (if they shared a
 * birthdate at RSVP) their Chinese zodiac. The message is generated by the API
 * and cached per attendee for the session, so it stays stable on re-render but
 * is unique to each guest.
 */
export default function ChappyGreeting({ eventSlug, phone }: { eventSlug: string; phone: string }) {
  const [greeting, setGreeting] = useState<string | null>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (!phone) return;
    const cacheKey = `chappy_greeting_${eventSlug}_${phone}`;
    let cancelled = false;

    async function run() {
      const cached = sessionStorage.getItem(cacheKey);
      if (cached) {
        if (!cancelled) setGreeting(cached);
        return;
      }
      try {
        const res = await fetch(
          `${BASE}/catering/events/${eventSlug}/greeting?phone=${encodeURIComponent(phone)}`
        );
        if (res.ok) {
          const data = await res.json();
          if (!cancelled && data.greeting) {
            sessionStorage.setItem(cacheKey, data.greeting);
            setGreeting(data.greeting);
          }
        }
      } catch {
        /* Chappy is optional delight — fail silently */
      }
    }
    run();
    return () => {
      cancelled = true;
    };
  }, [eventSlug, phone]);

  useEffect(() => {
    if (greeting) {
      const t = setTimeout(() => setVisible(true), 40);
      return () => clearTimeout(t);
    }
  }, [greeting]);

  if (!greeting) return null;

  return (
    <div
      style={{
        width: "100%",
        maxWidth: "420px",
        display: "flex",
        alignItems: "flex-start",
        gap: "12px",
        opacity: visible ? 1 : 0,
        animation: visible ? "chappyPopIn 0.5s ease both" : undefined,
      }}
    >
      {/* Avatar (zoomed on Chappy's face so his eyes show) + name label */}
      <div style={{ flexShrink: 0, display: "flex", flexDirection: "column", alignItems: "center", gap: "5px" }}>
        <div style={{ animation: "chappyBob 2.8s ease-in-out infinite" }}>
          <div
            role="img"
            aria-label="Chappy Chopstix"
            style={{
              width: 72,
              height: 72,
              borderRadius: "50%",
              background: "#FBF7F0 url('/Chappy.png') no-repeat",
              backgroundSize: "340%",
              backgroundPosition: "51% 17%",
              border: "2px solid var(--brand-border)",
              boxShadow: "0 2px 10px rgba(0,0,0,0.25)",
            }}
          />
        </div>
        <span
          style={{
            fontSize: "0.6rem",
            fontWeight: 700,
            letterSpacing: "0.5px",
            color: "var(--brand-primary)",
            opacity: 0.7,
            fontFamily: "'Raleway', sans-serif",
            whiteSpace: "nowrap",
          }}
        >
          Chappy Chopstix
        </span>
      </div>

      {/* Speech bubble */}
      <div
        style={{
          position: "relative",
          background: "var(--brand-surface)",
          border: "1px solid var(--brand-border)",
          borderRadius: "14px",
          padding: "12px 16px",
          flex: 1,
        }}
      >
        {/* Little tail pointing at Chappy */}
        <div
          style={{
            position: "absolute",
            left: "-6px",
            top: "18px",
            width: "12px",
            height: "12px",
            background: "var(--brand-surface)",
            borderLeft: "1px solid var(--brand-border)",
            borderBottom: "1px solid var(--brand-border)",
            transform: "rotate(45deg)",
          }}
        />
        <p
          style={{
            margin: 0,
            fontSize: "0.9rem",
            lineHeight: 1.5,
            color: "var(--brand-primary)",
            fontFamily: "'Raleway', sans-serif",
          }}
        >
          {greeting}
        </p>
      </div>
    </div>
  );
}
